import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { BlindsIcon, BookHeart, GalleryVerticalIcon } from "lucide-react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-rose-100 to-teal-100`}
      >
         
        {children}
        <nav className="space-x-4 mt-6 flex items-center justify-center p-4">
        <Link href="/" className="d transition-colors flex items-center gap-1">
          <BlindsIcon className="w-4 h-4" />
          Home
        </Link>
        <Link href="/gallery" className="d transition-colors flex items-center gap-1">
          <GalleryVerticalIcon className="w-4 h-4" />
          Gallery
        </Link>
        <Link href="/poem" className=" transition-colors flex items-center gap-1">
          <BookHeart className="w-4 h-4" />
          Poem
        </Link>
        
          <Link href="/love-quizy" className=" transition-colors flex items-center gap-1">
          <BookHeart className="w-4 h-4" />
          Love Quiz
        </Link>

      </nav>
      </body>
    </html>
  );
}
