import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { BlindsIcon, BookHeart, GalleryVerticalIcon } from "lucide-react";
import { Button } from "@/components/ui/button";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-rose-100 to-teal-100`}
      >

        {children}

        <div className="fixed bottom-8 right-8 space-x-4">
          <Button asChild variant="ghost">
            <a href="/">Home</a>
          </Button>
          <Button asChild variant="ghost">
            <a href="/love-quizy">Game My love</a>
          </Button>
          <Button asChild variant="ghost">
            <a href="/gallery">Gallery</a>
          </Button>
          <Button asChild variant="ghost">
            <a href="/poem">Our Poem</a>
          </Button>
        </div>

      </body>
    </html>
  );
}
